/**
 * providers.ts — LLM 厂商注册表（系统固定配置）
 *
 * 来源：cc-switch (https://github.com/farion1231/cc-switch) 的
 * claudeProviderPresets / codexProviderPresets 合并去重，
 * 同时保留原 8 家官方厂商的 OpenAI Chat Completions 兼容端点。
 *
 * 沙盒原则：本清单为系统固定配置；用户只能为每家填入自己的 API key
 * 与模型名（存 aiStore，仅本机）。
 */

export type ProviderKind = 'openai' | 'anthropic';

export interface ProviderDef {
  id: string;
  /** 显示名 */
  name: string;
  /** Chat Completions / Messages 端点的 base（不含路径尾） */
  baseUrl: string;
  kind: ProviderKind;
  /** 预设模型（用户可手填覆盖） */
  presetModels: string[];
  /** 获取 key 的控制台地址（设置页跳转提示用） */
  consoleUrl: string;
  /** Logo slug（对应 public/logos/ 文件名，不含扩展名） */
  logo?: string | null;
  /** 品牌色 (hex) */
  iconColor?: string | null;
  /** 色板次要色 (hex) */
  color?: string | null;
  /** 分类（official / cn_official / aggregator / third_party / cloud_provider） */
  category?: string | null;
  /** 中文名 */
  cn?: string | null;
}

export const PROVIDERS: ProviderDef[] = [
  // ──────────────────────────────────────────────
  // 1. 官方厂商 — OpenAI Chat Completions 兼容
  // ──────────────────────────────────────────────
  {
    id: 'openai',
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    kind: 'openai',
    presetModels: ['gpt-4o-mini', 'gpt-4o', 'gpt-5.5', 'o3-mini'],
    consoleUrl: 'https://platform.openai.com',
    logo: 'openai', iconColor: '#000000', color: '#000000',
    category: 'official', cn: 'OpenAI',
  },
  {
    id: 'claude',
    name: 'Claude (Anthropic)',
    baseUrl: 'https://api.anthropic.com/v1',
    kind: 'anthropic',
    presetModels: ['claude-sonnet-4-6', 'claude-haiku-4-5-20251001', 'claude-opus-4-8'],
    consoleUrl: 'https://console.anthropic.com',
    logo: 'claude', iconColor: '#D97757', color: '#D97757',
    category: 'official', cn: 'Anthropic',
  },
  {
    id: 'gemini',
    name: 'Gemini (Google)',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    kind: 'openai',
    presetModels: ['gemini-2.0-flash', 'gemini-2.5-pro', 'gemini-3.5-flash'],
    consoleUrl: 'https://aistudio.google.com',
    logo: 'gemini', iconColor: '#4285F4', color: '#4285F4',
    category: 'official', cn: 'Google',
  },

  // ──────────────────────────────────────────────
  // 2. 中国官方厂商
  // ──────────────────────────────────────────────
  {
    id: 'deepseek',
    name: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com/v1',
    kind: 'openai',
    presetModels: ['deepseek-chat', 'deepseek-reasoner'],
    consoleUrl: 'https://platform.deepseek.com',
    logo: 'deepseek', iconColor: '#4F6BED', color: '#4F6BED',
    category: 'cn_official', cn: '深度求索',
  },
  {
    id: 'kimi',
    name: 'Kimi (月之暗面)',
    baseUrl: 'https://api.moonshot.cn/v1',
    kind: 'openai',
    presetModels: ['moonshot-v1-8k', 'kimi-latest', 'kimi-k2.7-code'],
    consoleUrl: 'https://platform.moonshot.cn',
    logo: 'kimi', iconColor: '#6366F1', color: '#6366F1',
    category: 'cn_official', cn: '月之暗面',
  },
  {
    id: 'kimi-coding',
    name: 'Kimi For Coding',
    baseUrl: 'https://api.kimi.com/coding',
    kind: 'openai',
    presetModels: ['kimi-k2.7-code'],
    consoleUrl: 'https://www.kimi.com/code/docs',
    logo: 'kimi', iconColor: '#6366F1', color: '#6366F1',
    category: 'cn_official', cn: 'Kimi 编程版',
  },
  {
    id: 'zhipu',
    name: 'GLM (智谱)',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    kind: 'openai',
    presetModels: ['glm-4-flash', 'glm-4-plus', 'glm-5.1'],
    consoleUrl: 'https://open.bigmodel.cn',
    logo: 'zhipu', iconColor: '#2868F5', color: '#2868F5',
    category: 'cn_official', cn: '智谱 AI',
  },
  {
    id: 'qwen',
    name: 'Qwen (通义千问)',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    kind: 'openai',
    presetModels: ['qwen-plus', 'qwen-turbo', 'qwen-max'],
    consoleUrl: 'https://bailian.console.aliyun.com',
    logo: 'qwen', iconColor: '#6A5ACD', color: '#6A5ACD',
    category: 'cn_official', cn: '阿里云',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    baseUrl: 'https://api.minimax.chat/v1',
    kind: 'openai',
    presetModels: ['MiniMax-Text-01', 'MiniMax-M2.7'],
    consoleUrl: 'https://platform.minimaxi.com',
    logo: 'minimax', iconColor: '#FF6B6B', color: '#FF6B6B',
    category: 'cn_official', cn: '稀宇科技',
  },
  {
    id: 'bailian',
    name: '阿里云百炼',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    kind: 'openai',
    presetModels: ['qwen-plus', 'qwen-max'],
    consoleUrl: 'https://bailian.console.aliyun.com',
    logo: 'bailian', iconColor: '#624AFF', color: '#624AFF',
    category: 'cn_official', cn: '阿里云百炼',
  },
  {
    id: 'bailian-coding',
    name: 'Bailian For Coding',
    baseUrl: 'https://coding.dashscope.aliyuncs.com/compatible-mode/v1',
    kind: 'openai',
    presetModels: ['qwen-coding-plus'],
    consoleUrl: 'https://bailian.console.aliyun.com',
    logo: 'bailian', iconColor: '#624AFF', color: '#624AFF',
    category: 'cn_official', cn: '百炼编程版',
  },
  {
    id: 'baidu',
    name: '百度千帆',
    baseUrl: 'https://qianfan.baidubce.com/v2',
    kind: 'openai',
    presetModels: ['ERNIE-4.5', 'ERNIE-3.5'],
    consoleUrl: 'https://cloud.baidu.com/product/qianfan_modelbuilder',
    logo: 'baidu', iconColor: '#2932E1', color: '#2932E1',
    category: 'cn_official', cn: '百度智能云',
  },
  {
    id: 'baidu-coding',
    name: 'Baidu Qianfan Coding Plan',
    baseUrl: 'https://qianfan.baidubce.com/anthropic/coding',
    kind: 'openai',
    presetModels: ['qianfan-code-latest'],
    consoleUrl: 'https://cloud.baidu.com/product/qianfan_modelbuilder',
    logo: 'baidu', iconColor: '#2932E1', color: '#2932E1',
    category: 'cn_official', cn: '百度千帆编程',
  },
  {
    id: 'stepfun',
    name: 'StepFun (阶跃星辰)',
    baseUrl: 'https://api.stepfun.com/v1',
    kind: 'openai',
    presetModels: ['step-2', 'step-3.5-flash'],
    consoleUrl: 'https://platform.stepfun.com',
    logo: 'stepfun', iconColor: '#16D6D2', color: '#16D6D2',
    category: 'cn_official', cn: '阶跃星辰',
  },
  {
    id: 'huoshan',
    name: '火山引擎 Agentplan',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/coding',
    kind: 'openai',
    presetModels: ['ark-code-latest'],
    consoleUrl: 'https://www.volcengine.com/activity/codingplan',
    logo: 'huoshan', iconColor: '#3370FF', color: '#3370FF',
    category: 'cn_official', cn: '火山引擎',
  },
  {
    id: 'byteplus',
    name: 'BytePlus',
    baseUrl: 'https://ark.ap-southeast.bytepluses.com/api/coding',
    kind: 'openai',
    presetModels: ['ark-code-latest'],
    consoleUrl: 'https://www.byteplus.com/en/product/modelark',
    logo: 'byteplus', iconColor: '#3370FF', color: '#3370FF',
    category: 'cn_official', cn: 'BytePlus',
  },
  {
    id: 'doubao-seed',
    name: 'DouBaoSeed (豆包)',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/compatible',
    kind: 'openai',
    presetModels: ['doubao-seed-2-0-code-preview-latest'],
    consoleUrl: 'https://console.volcengine.com/ark',
    logo: 'doubao', iconColor: '#3370FF', color: '#3370FF',
    category: 'cn_official', cn: '豆包大模型',
  },
  {
    id: 'catcoder',
    name: 'KAT-Coder',
    baseUrl: 'https://vanchin.streamlake.ai/api/gateway/v1/endpoints/v1',
    kind: 'openai',
    presetModels: ['KAT-Coder-Pro V1', 'KAT-Coder-Air V1'],
    consoleUrl: 'https://console.streamlake.ai',
    logo: 'catcoder', iconColor: '#000000', color: '#000000',
    category: 'cn_official', cn: 'KAT-Coder',
  },
  {
    id: 'longcat',
    name: 'Longcat',
    baseUrl: 'https://api.longcat.chat/anthropic',
    kind: 'openai',
    presetModels: ['LongCat-Flash-Chat'],
    consoleUrl: 'https://longcat.chat/platform',
    logo: 'longcat', iconColor: '#29E154', color: '#29E154',
    category: 'cn_official', cn: 'Longcat',
  },
  {
    id: 'xiaomimimo',
    name: 'Xiaomi MiMo (小米)',
    baseUrl: 'https://api.xiaomimimo.com/anthropic',
    kind: 'openai',
    presetModels: ['mimo-v2.5-pro'],
    consoleUrl: 'https://platform.xiaomimimo.com',
    logo: 'xiaomimimo', iconColor: '#000000', color: '#000000',
    category: 'cn_official', cn: '小米 MiMo',
  },
  {
    id: 'xiaomimimo-token',
    name: 'Xiaomi MiMo Token Plan (China)',
    baseUrl: 'https://token-plan-cn.xiaomimimo.com/anthropic',
    kind: 'openai',
    presetModels: ['mimo-v2.5-pro'],
    consoleUrl: 'https://platform.xiaomimimo.com/#/token-plan',
    logo: 'xiaomimimo', iconColor: '#000000', color: '#000000',
    category: 'cn_official', cn: '小米 MiMo 算力包',
  },
  {
    id: 'bailing',
    name: 'BaiLing (支付宝 Ling)',
    baseUrl: 'https://api.tbox.cn/api/anthropic',
    kind: 'openai',
    presetModels: ['Ling-2.5-1T'],
    consoleUrl: 'https://alipaytbox.yuque.com/sxs0ba/ling/get_started',
    logo: null, iconColor: '#1677FF', color: '#1677FF',
    category: 'cn_official', cn: '支付宝 Ling',
  },

  // ──────────────────────────────────────────────
  // 3. API 聚合 / 网关
  // ──────────────────────────────────────────────
  {
    id: 'openrouter',
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://openrouter.ai/keys',
    logo: 'openrouter', iconColor: '#6566F1', color: '#6566F1',
    category: 'aggregator', cn: 'OpenRouter',
  },
  {
    id: 'therouter',
    name: 'TheRouter',
    baseUrl: 'https://api.therouter.ai/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://dashboard.therouter.ai',
    logo: null, iconColor: '#000000', color: '#000000',
    category: 'aggregator', cn: 'TheRouter',
  },
  {
    id: 'shengsuanyun',
    name: '胜算云',
    baseUrl: 'https://router.shengsuanyun.com/api',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://www.shengsuanyun.com',
    logo: 'shengsuanyun', iconColor: '#000000', color: '#000000',
    category: 'aggregator', cn: '胜算云',
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow (硅基流动)',
    baseUrl: 'https://api.siliconflow.cn/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://cloud.siliconflow.cn',
    logo: 'siliconflow', iconColor: '#6E29F6', color: '#6E29F6',
    category: 'aggregator', cn: '硅基流动',
  },
  {
    id: 'aihubmix',
    name: 'AiHubMix',
    baseUrl: 'https://aihubmix.com/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://aihubmix.com',
    logo: 'aihubmix', iconColor: '#006FFB', color: '#006FFB',
    category: 'aggregator', cn: 'AiHubMix',
  },
  {
    id: 'modelscope',
    name: 'ModelScope (魔搭)',
    baseUrl: 'https://api-inference.modelscope.cn/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://modelscope.cn',
    logo: 'modelscope', iconColor: '#624AFF', color: '#624AFF',
    category: 'aggregator', cn: '魔搭社区',
  },
  {
    id: 'novita',
    name: 'Novita AI',
    baseUrl: 'https://api.novita.ai/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://novita.ai',
    logo: 'novita', iconColor: '#000000', color: '#000000',
    category: 'aggregator', cn: 'Novita AI',
  },
  {
    id: 'nvidia',
    name: 'Nvidia NIM',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://build.nvidia.com',
    logo: 'nvidia', iconColor: '#000000', color: '#000000',
    category: 'aggregator', cn: 'NVIDIA',
  },
  {
    id: 'ccsub',
    name: 'CCSub',
    baseUrl: 'https://www.ccsub.net/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://www.ccsub.net',
    logo: 'ccsub', iconColor: '#000000', color: '#000000',
    category: 'aggregator', cn: 'CCSub',
  },
  {
    id: 'unity2',
    name: 'Unity2.ai',
    baseUrl: 'https://api.unity2.ai/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://unity2.ai',
    logo: 'unity2', iconColor: '#000000', color: '#000000',
    category: 'aggregator', cn: 'Unity2',
  },
  {
    id: 'cherryin',
    name: 'CherryIN',
    baseUrl: 'https://open.cherryin.net/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://open.cherryin.ai',
    logo: 'cherryin', iconColor: '#000000', color: '#000000',
    category: 'aggregator', cn: 'CherryIN',
  },
  {
    id: 'dmxapi',
    name: 'DMXAPI',
    baseUrl: 'https://www.dmxapi.cn/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://www.dmxapi.cn',
    logo: null, iconColor: '#000000', color: '#000000',
    category: 'aggregator', cn: 'DMXAPI',
  },
  {
    id: 'pipellm',
    name: 'PIPELLM',
    baseUrl: 'https://cc-api.pipellm.ai',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://code.pipellm.ai',
    logo: 'pipellm', iconColor: '#000000', color: '#000000',
    category: 'aggregator', cn: 'PIPELLM',
  },
  {
    id: 'newapi',
    name: 'NewAPI',
    baseUrl: 'https://api.newapi.pro/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://www.newapi.pro',
    logo: 'newapi', iconColor: '#00A67E', color: '#00A67E',
    category: 'aggregator', cn: 'NewAPI',
  },
  {
    id: 'atlascloud',
    name: 'AtlasCloud',
    baseUrl: 'https://api.atlascloud.ai/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://www.atlascloud.ai',
    logo: 'atlascloud', iconColor: '#000000', color: '#000000',
    category: 'aggregator', cn: 'AtlasCloud',
  },
  {
    id: 'compshare',
    name: 'Compshare (UCloud)',
    baseUrl: 'https://api.modelverse.cn/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://www.compshare.cn',
    logo: 'ucloud', iconColor: '#000000', color: '#000000',
    category: 'aggregator', cn: 'UCloud 优刻得',
  },
  {
    id: 'compshare-coding',
    name: 'Compshare Coding Plan',
    baseUrl: 'https://cp.compshare.cn/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://www.compshare.cn/coding-plan',
    logo: 'ucloud', iconColor: '#000000', color: '#000000',
    category: 'aggregator', cn: 'UCloud 编程版',
  },

  // ──────────────────────────────────────────────
  // 4. 第三方服务商
  // ──────────────────────────────────────────────
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    baseUrl: 'https://api.githubcopilot.com',
    kind: 'openai',
    presetModels: ['claude-sonnet-4-6', 'gpt-5.5'],
    consoleUrl: 'https://github.com/features/copilot',
    logo: 'githubcopilot', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'GitHub Copilot',
  },
  {
    id: 'codex',
    name: 'OpenAI Codex',
    baseUrl: 'https://chatgpt.com/backend-api/codex',
    kind: 'openai',
    presetModels: ['gpt-5.5'],
    consoleUrl: 'https://openai.com/chatgpt/pricing',
    logo: 'openai', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'OpenAI Codex',
  },
  {
    id: 'pateway',
    name: 'PatewayAI',
    baseUrl: 'https://api.pateway.ai/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://pateway.ai',
    logo: 'pateway', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'PatewayAI',
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    baseUrl: 'https://opencode.ai/zen/go',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://opencode.ai',
    logo: 'opencode', iconColor: '#211E1E', color: '#211E1E',
    category: 'third_party', cn: 'OpenCode',
  },
  {
    id: 'packycode',
    name: 'PackyCode',
    baseUrl: 'https://www.packyapi.com/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://www.packyapi.com',
    logo: 'packycode', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'PackyCode',
  },
  {
    id: 'apikeyfun',
    name: 'APIKEY.FUN',
    baseUrl: 'https://api.apikey.fun/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://apikey.fun',
    logo: 'apikeyfun', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'APIKEY.FUN',
  },
  {
    id: 'apinebula',
    name: 'APINebula',
    baseUrl: 'https://apinebula.com/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://apinebula.com',
    logo: 'apinebula', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'APINebula',
  },
  {
    id: 'sudocode',
    name: 'SudoCode',
    baseUrl: 'https://sudocode.us/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://sudocode.us',
    logo: 'sudocode', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'SudoCode',
  },
  {
    id: 'claudeapi',
    name: 'ClaudeAPI',
    baseUrl: 'https://gw.claudeapi.com/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://claudeapi.com',
    logo: null, iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'ClaudeAPI',
  },
  {
    id: 'claudecn',
    name: 'ClaudeCN',
    baseUrl: 'https://claudecn.top/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://claudecn.top',
    logo: 'claudecn', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'ClaudeCN',
  },
  {
    id: 'runapi',
    name: 'RunAPI',
    baseUrl: 'https://runapi.co/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://runapi.co',
    logo: 'runapi', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'RunAPI',
  },
  {
    id: 'relaxcode',
    name: 'RelaxyCode',
    baseUrl: 'https://www.relaxycode.com/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://www.relaxycode.com',
    logo: 'relaxcode', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'RelaxyCode',
  },
  {
    id: 'cubence',
    name: 'Cubence',
    baseUrl: 'https://api.cubence.com/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://cubence.com',
    logo: 'cubence', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'Cubence',
  },
  {
    id: 'aigocode',
    name: 'AIGoCode',
    baseUrl: 'https://api.aigocode.com/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://aigocode.com',
    logo: 'aigocode', iconColor: '#5B7FFF', color: '#5B7FFF',
    category: 'third_party', cn: 'AIGoCode',
  },
  {
    id: 'rightcode',
    name: 'RightCode',
    baseUrl: 'https://www.right.codes/claude',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://www.right.codes',
    logo: 'rc', iconColor: '#E96B2C', color: '#E96B2C',
    category: 'third_party', cn: 'RightCode',
  },
  {
    id: 'aicodemirror',
    name: 'AICodeMirror',
    baseUrl: 'https://api.aicodemirror.com/api/claudecode',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://www.aicodemirror.com',
    logo: 'aicodemirror', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'AICodeMirror',
  },
  {
    id: 'crazyrouter',
    name: 'CrazyRouter',
    baseUrl: 'https://cn.crazyrouter.com/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://www.crazyrouter.com',
    logo: 'crazyrouter', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'CrazyRouter',
  },
  {
    id: 'sssaicode',
    name: 'SSSAiCode',
    baseUrl: 'https://node-hk.sssaicodeapi.com/api',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://sssaicodeapi.com',
    logo: 'sssaicode', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'SSSAiCode',
  },
  {
    id: 'micu',
    name: 'Micu',
    baseUrl: 'https://www.micuapi.ai/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://www.micuapi.ai',
    logo: 'micu', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'Micu',
  },
  {
    id: 'ctok',
    name: 'CTok.ai',
    baseUrl: 'https://api.ctok.ai/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://ctok.ai',
    logo: 'ctok', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'CTok',
  },
  {
    id: 'eflowcode',
    name: 'E-FlowCode',
    baseUrl: 'https://e-flowcode.cc/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://e-flowcode.cc',
    logo: 'eflowcode', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'E-FlowCode',
  },
  {
    id: 'zenmux',
    name: 'ZenMux',
    baseUrl: 'https://api.zenmux.com/v1',
    kind: 'openai',
    presetModels: [],
    consoleUrl: 'https://zenmux.com',
    logo: 'zenmux', iconColor: '#000000', color: '#000000',
    category: 'third_party', cn: 'ZenMux',
  },

  // ──────────────────────────────────────────────
  // 5. 云平台
  // ──────────────────────────────────────────────
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    baseUrl: 'https://bedrock-runtime.us-west-2.amazonaws.com',
    kind: 'openai',
    presetModels: ['claude-opus-4-8', 'claude-sonnet-4-6'],
    consoleUrl: 'https://aws.amazon.com/bedrock/',
    logo: 'aws', iconColor: '#FF9900', color: '#FF9900',
    category: 'cloud_provider', cn: 'AWS Bedrock',
  },
];

export function getProvider(id: string): ProviderDef | undefined {
  return PROVIDERS.find((p) => p.id === id);
}

/** 厂商预设模型映射表 */
export const MODELS_BY_PROVIDER: Record<string, string[]> = {};
for (const p of PROVIDERS) {
  MODELS_BY_PROVIDER[p.id] = p.presetModels;
}

/** 获取厂商预设模型列表 */
export function getDefaultModels(providerId: string): string[] {
  return MODELS_BY_PROVIDER[providerId] ?? [];
}
